################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Case-level cross-sectional time-series data by department
#' 
#' This dataset includes aggregated data on the number of infringement cases
#' per department per year (cross-sectional time-series data). There is one
#' observation per department per year (2002-2020).
#' 
#' @format A data frame with 6 variables:
#' \describe{
#' \item{key_id}{\\code\{numeric\}. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{\\code\{numeric\}. The year the case was opened by the
#' Commission.}
#' \item{department_id}{\\code\{numeric\}. An ID number that uniquely
#' identifies each Commission department.}
#' \item{department}{\\code\{string\}. The name of the Commission department
#' that opened the infringement case.}
#' \item{department_code}{\\code\{string\}. A multi-letter code assigned by
#' the Commission that uniquely identifies each department.}
#' \item{count_cases}{\\code\{numeric\}. A count of the number of cases opened
#' by the Commission at this level of aggregation.}
#' }
"cases_csts_dp"

################################################################################
# end R script
################################################################################

