################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Case-level time-series data
#' 
#' This dataset includes aggregated data on the number of infringement cases
#' per year (time-series data). There is one observation per year (2002-2020).
#' 
#' @format A data frame with 3 variables:
#' \describe{
#' \item{key_id}{\\code\{numeric\}. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{\\code\{numeric\}. The year the case was opened by the
#' Commission.}
#' \item{count_cases}{\\code\{numeric\}. A count of the number of cases opened
#' by the Commission at this level of aggregation.}
#' }
"cases_ts"

################################################################################
# end R script
################################################################################

