################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Case-level cross-sectional time-series data by member state
#' 
#' This dataset includes aggregated data on the number of infringement cases
#' per member state per year (cross-sectional time-series data). There is one
#' observation per member state per year (2002-2020), excluding state-years
#' where the state was not a member of the EU.
#' 
#' @format A data frame with 6 variables:
#' \describe{
#' \item{key_id}{\\code\{numeric\}. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{\\code\{numeric\}. The year the case was opened by the
#' Commission.}
#' \item{member_state_id}{\\code\{numeric\}. An ID number that uniquely
#' identifies each member state. This ID number is assigned when member states
#' are sorted by accession date and then alphabetically. }
#' \item{member_state}{\\code\{string\}. The name of the member state that the
#' Commission opened the case against. }
#' \item{member_state_code}{\\code\{string\}. A two letter code assigned by
#' the Commission that uniquely identifies each member state. }
#' \item{count_cases}{\\code\{numeric\}. A count of the number of cases opened
#' by the Commission at this level of aggregation.}
#' }
"cases_csts_ms"

################################################################################
# end R script
################################################################################

