################################################################################
# Joshua C. Fjelstul, Ph.D.
# ecio R package
# automatically generated by the codebookr R package
################################################################################

#' Decision-level data
#' 
#' This dataset include data on infringement decisions. There is one
#' observation per decision per case (2002-2020). The dataset includes
#' information on the department responsible for the decision and the member
#' state that the decision is against.
#' 
#' @format A data frame with 34 variables:
#' \describe{
#' \item{key_id}{\\code\{numeric\}. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{decision_id}{\\code\{numeric\}. An ID number that uniquely identifies
#' each decision in an infringement case.}
#' \item{case_id}{\\code\{string\}. An ID number that uniquely identifies each
#' case.}
#' \item{case_number}{\\code\{numeric\}. The number of the case.}
#' \item{case_year}{\\code\{numeric\}. The year of the case.}
#' \item{decision_date}{\\code\{date\}. The date that the Commission issued
#' the decision in the format \code{YYYY-MM-DD}.}
#' \item{decision_year}{\\code\{numeric\}. The year that the Commission issued
#' the decision.}
#' \item{decision_month}{\\code\{numeric\}. The month that the Commission
#' issued the decision.}
#' \item{decision_day}{\\code\{numeric\}. The day that the Commission issued
#' the decision.}
#' \item{member_state_id}{\\code\{numeric\}. An ID number that uniquely
#' identifies each member state. This ID number is assigned when member states
#' are sorted by accession date and then alphabetically. }
#' \item{member_state}{\\code\{string\}. The name of the member state that the
#' Commission opened the case against. }
#' \item{member_state_code}{\\code\{string\}. A two letter code assigned by
#' the Commission that uniquely identifies each member state. }
#' \item{department_id}{\\code\{numeric\}. An ID number that uniquely
#' identifies each Commission department.}
#' \item{department}{\\code\{string\}. The name of the Commission department
#' that opened the infringement case.}
#' \item{department_code}{\\code\{string\}. A multi-letter code assigned by
#' the Commission that uniquely identifies each department.}
#' \item{case_type_id}{\\code\{numeric\}. An ID number that uniquely
#' identifies each type of state aid cases. Coded \code{1} for
#' noncommunication cases, which are cases that relate to a member state
#' failing to notify the Commission that it has transposed a directive by the
#' stated deadline. Coded \code{2} for nonconformity cases, which are cases
#' that relate to a member state incorrectly transposing a directive. }
#' \item{case_type}{\\code\{string\}. The type of the infringement case. There
#' are two types of cases. Coded \code{noncommunication} for cases that relate
#' to a member state failing to notify the Commission that it has transposed a
#' directive by the stated deadline. Coded \code{nonconformity} for cases that
#' relate to a member state incorrectly transposing a directive. }
#' \item{noncommunication}{\\code\{dummy\}. A dummy variable indicating
#' whether the infringement case is a noncommunication case, which is a case
#' that relates to a member state failing to notify that Commission that it
#' has transposed a directive by the stated deadline.}
#' \item{nonconformity}{\\code\{dummy\}. A dummy variable indicating whether
#' the infringement case is a nonconformity case, which is a case that relates
#' to a member state incorrectly transposing a directive.}
#' \item{directive}{\\code\{dummy\}. A dummy variable indicating whether the
#' description of the infringement case provided by the Commission references
#' a directive that the case relates to. Directive numbers have the format
#' \code{####/####}, where the first set of numbers is the year the directive
#' was enacted and the second set is the number of the directive.}
#' \item{directive_number}{\\code\{string\}. The number of the directive that
#' the infringement case relates to, if applicable. Coded \code{NA} if the
#' description of the case provided by the Commission does not reference a
#' specific directive number.}
#' \item{celex}{\\code\{string\}. The CELEX number of the directive that the
#' infringement case relates to, if applicable. Coded \code{NA} if the
#' description of the case provided by the Commission does not reference a
#' specific directive number. CELEX numbers for directives have the format
#' \code{3####L####}, where the first set of numbers is the year the directive
#' was enacted and the second set is the number of the directive.}
#' \item{decision_stage_id}{\\code\{numeric\}. An ID number that uniquely
#' identifies each decision stage in the infringement procedure. Coded
#' \code{1} for letters of formal notice under Article 258 of the Treaty on
#' the Functioning of the European Union (TFEU), coded \code{2} for reasoned
#' opinions under Article 258, coded \code{3} for referrals to the Court of
#' Justice of the European Union (CJEU) under Article 258, coded \code{4} for
#' letters of formal notice under Article 260, coded \code{5} for reasoned
#' opinions under Article 260, and coded \code{6} for referrals to the Court
#' under Article 260.}
#' \item{decision_stage}{\\code\{string\}. The decision stage of the
#' infringement procedure. Possible values include: \code{Letter of formal
#' notice (Article 258)}, \code{Reasoned opinion (Article 259)},
#' \code{Referral to the Court (Article 258)}, \code{Letter of formal notice
#' (Article 260)}, \code{Reasoned opinion (Article 260)}, and \code{Referral
#' to the Court (Article 260)}.}
#' \item{stage_lfn_258}{\\code\{dummy\}. A dummy variable indicating whether
#' the decision is a letter of formal notice sent by the Commission under
#' Article 258 of the Treaty on the Functioning of the European Union (TFEU).}
#' \item{stage_ro_258}{\\code\{dummy\}. A dummy variable indicating whether
#' the decision is a reasoned opinion sent by the Commission under Article 258
#' of the Treaty on the Functioning of the European Union (TFEU).}
#' \item{stage_rf_258}{\\code\{dummy\}. A dummy variable indicating whether
#' the decision is a referral to the Court of Justice of the European Union
#' (CJEU) made by the Commission under Article 258 of the Treaty on the
#' Functioning of the European Union (TFEU).}
#' \item{stage_lfn_260}{\\code\{dummy\}. A dummy variable indicating whether
#' the decision is a letter of formal notice sent by the Commission under
#' Article 260 of the Treaty on the Functioning of the European Union (TFEU).}
#' \item{stage_ro_260}{\\code\{dummy\}. A dummy variable indicating whether
#' the decision is a reasoned opinion sent by the Commission under Article 260
#' of the Treaty on the Functioning of the European Union (TFEU).}
#' \item{stage_rf_260}{\\code\{dummy\}. A dummy variable indicating whether
#' the decision is a referral to the Court of Justice of the European Union
#' (CJEU) made by the Commission under Article 260 of the Treaty on the
#' Functioning of the European Union (TFEU).}
#' \item{stage_closing}{\\code\{dummy\}. A dummy variable indicating whether
#' the decision is the closing of the case by the Commission. }
#' \item{stage_withdrawal}{\\code\{dummy\}. A dummy variable indicating
#' whether the decision is the withdrawal of the case by the Commission.}
#' \item{stage_additional}{\\code\{dummy\}. A dummy variable indicating
#' whether the decision is an additional decision (a decision of the same type
#' as a previous decision). }
#' \item{press_release}{\\code\{dummy\}. A dummy variable indicating whether
#' the Commission published a press release to publicize the decision.}
#' }
"decisions"

################################################################################
# end R script
################################################################################

