################################################################################
# Joshua C. Fjelstul, Ph.D.
# codebookr R package
################################################################################

#' Create dataset documentation
#'
#' This function generates \code{R} documentation for one or more datasets. You
#' need to provide a data frame with a description of each dataset and a data
#' frame with a description of each variable. Whenever you update these data
#' frames, you can easily regenerate the \code{R} documentation without making
#' the changes in multiple places. Running this function generates one \code{.R}
#' file per dataset and saves these files in the folder indicated by the
#' \code{path} argument. If you're developing an \code{R} package, this path
#' should be to the \code{R/} folder in your package directory. After you run
#' \code{document_data()} to produce an \code{.R} file for each dataset, you can
#' run \code{roxygen2} using \code{devetools::document()} to generate a
#' \code{.Rd} (\code{R} documentation) file for each dataset. These \code{.Rd}
#' files will be saved to the \code{man/} folder, as usual.
#'
#' @param datasets_input A data frame containing information on each dataset.
#'   This data frame must include: (1) a variable called \code{dataset} that is
#'   the name of each dataset, which will be used as the heading for each
#'   dataset section; (2) a variable called \code{label} that is a short label
#'   for each dataset (one line), which will be used as the subheading for each
#'   dataset section; and (3) a variable called \code{description} that is a
#'   description of each dataset, which will be included before the description
#'   of each variable. Text wrapped in braces will be formatted as code. The
#'   dataset names should be valid \code{R} object names.
#' @param variables_input A data frame containing infromation on each variable.
#'   This data frame must include: (1) a variable called \code{dataset}, where
#'   each dataset maps exactly to the datasets in the \code{dataset} variable in
#'   the \code{datasets_input} data frame; and (2) a variable called
#'   \code{description} that is a description of each variable. Text wrapped in
#'   braces will be formatted as code. Optionally, the data frame can include a
#'   variable called \code{type} that indicates the type of each variable (e.g.,
#'   numeric, string, etc.). If this variable is included, and the
#'   \code{include_variable_type} argument is set to \code{TRUE}, then the
#'   variable type will be included at the beginning of each variable
#'   description.
#' @param file_path The path to the folder where the output file should be
#'   saved. If you're developing an \code{R} package and you're working
#'   directory is set to the project directory, this argument should be
#'   \code{"R/"}.
#' @param include_variable_type A logical value indicating whether to include
#'   the type of the variable in the variable description. The
#'   \code{variables_input} data frame must have a variable called \code{type}
#'   or you will get an error.
#' @param author Optional. A string or string vector indicating the name of the
#'   package author(s). If provided, these names will be included in the header
#'   of each \code{.R} file produced.
#' @param package Optional. A string indicating the name of the package that the
#'   data will be distributed in. If provided, the name of the package will be
#'   included in the header of each \code{.R} file produced.
#' @export
document_data <- function(file_path, variables_input, datasets_input, include_variable_type = FALSE, author = NULL, package = NULL) {

  # author
  if(!is.null(author)) {
    author <- stringr::str_c("# ", author)
  }

  # package
  if(!is.null(package)) {
    package <- stringr::str_c("# ", package, " R package")
  }

  # make an empty list to store documents
  documents <- list()

  # loop through each dataset
  for(i in 1:nrow(datasets_input)) {

    # metadata for dataset
    variables_subset <- dplyr::filter(variables_input, dataset == datasets_input$dataset[i])
    variables_subset$description <- stringr::str_replace_all(variables_subset$description, "\\{(.*?)\\}", "\\\\code\\{\\1\\}")

    # file header
    header <- c(
      "################################################################################",
      author,
      package,
      "# automatically generated by the codebookr R package",
      "################################################################################",
      ""
    )

    # label
    label <- datasets_input$label[i]

    # description
    description <- datasets_input$description[[i]]
    description <- stringr::str_c(description, collapse = "\n")

    # format
    format <- stringr::str_c("@format A data frame with ", nrow(variables_subset), " variables:")

    # variables
    if (include_variable_type) {
      variables <- stringr::str_c(
        "\\item{", variables_subset$variable, "}",
        "{", "\\\\code\\{", variables_subset$type, "\\}. ", variables_subset$description, "}"
      )
    } else {
      variables <- stringr::str_c(
        "\\item{", variables_subset$variable, "}",
        "{", variables_subset$description, "}"
      )
    }

    # describe
    describe <- c("\\describe{", variables, "}")
    describe <- stringr::str_c(describe, collapse = "\n")

    # dataset
    dataset <- stringr::str_c("\"", datasets_input$dataset[i], "\"")

    # file footer
    footer <- c(
      "",
      "################################################################################",
      "# end R script",
      "################################################################################",
      ""
    )

    # comments
    comments <- stringr::str_c(
      label, "\n\n", description, "\n\n", format, "\n", describe
    )
    comments <- reflow_comment(comments)

    # build document
    document <- c(
      header,
      comments,
      dataset,
      footer
    )

    # add to documents
    documents[[i]] <- document
  }

  # save documents
  for(i in 1:nrow(datasets_input)) {

    # file output
    output <- documents[[i]]

    # file name
    file <- stringr::str_c(datasets_input$dataset[i], ".R")

    # write R file to working directory
    writeLines(output, stringr::str_c(file_path, file))
  }

  # message
  cat("documents saved to working directory")
}

################################################################################
# end R script
################################################################################
